[package]

name = "pipeline"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.71"
futures = "0.3.28"

[dev-dependencies]
tokio = { version = "1.28.1", features = ["full"] }
thingbuf = { version = "0.1.4", features = ["std", "alloc"] }
