[package]

name = "pipeline"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.71"
thingbuf = { version = "0.1.4", features = ["std", "alloc"] }
tokio = { version = "1.28.1", features = ["full"] }
futures = "0.3.28"
async-executor = "1.5.1"
derivative = "2.2.0"
